enum ActionTypes {
	SET_SETTINGS_VISIBILITY,
	TOGGLE_SETTINGS_VISIBILITY,
	
	SET_CANVAS_COLOR,
	TOGGLE_CANVAS_COLOR,
	
	SET_ONSET_DETECTION_RUNNING,
	TOGGLE_ONSET_DETECTION_RUNNING,
	SET_ONSET_DATA,
	SET_ONSET_GRAPH_SCALE,
	
	SET_THRESHOLD,
	TOGGLE_AUTO_THRESHOLD_IS_ACTIVE,
}

export default ActionTypes;
