export const SET_SETTINGS_VISIBILITY = 'SET_SETTINGS_VISIBILITY';
export const TOGGLE_SETTINGS_VISIBILITY = 'TOGGLE_SETTINGS_VISIBILITY';

export const SET_CANVAS_COLOR = 'SET_CANVAS_COLOR';
export const TOGGLE_CANVAS_COLOR = 'TOGGLE_CANVAS_COLOR';

export const SET_ONSET_DETECTION_RUNNING = 'SET_ONSET_DETECTION_RUNNING';
export const TOGGLE_ONSET_DETECTION_RUNNING = 'TOGGLE_ONSET_DETECTION_RUNNING';
export const SET_ONSET_DATA = 'SET_ONSET_DATA';
